[workspace]
authors = ["Mose Schmiedel <mose@schmiednet.de>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "qr-gen"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
qrcode = ">=8.2,<9"
yt-dlp = ">=2025.10.22,<2026"
