[workspace]
authors = ["Mose Schmiedel <mose@schmiednet.de>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "qr-gen"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
yt-dlp = ">=2025.10.22,<2026"
pathvalidate = ">=3.3.1,<4"

[pypi-dependencies]
qrcode = { version = "*", extras = ["pil"] }
